### ISSUE TITLE
Contenido de programación en Paralelo

### ISSUE THREAD

**Issue by spsaaibi** [ComputoCienciasUniandes/MetodosComputacionalesAvanzados#1]
@forero puede ser útil para pensar en el contenido de un curso de programación en paralelo: http://ait.inf.ethz.ch/teaching/courses/2014-SS-Parallel-Programming/

**Comment by forero** [comment]
@spsaaibi esta excelente el link. Ahora que ya estoy preparando temas y dictando el curso el enlace me cae muy bien. Tal vez le pida el favor de darme una mano con un par de clases de machine learning por hangout!

**Comment by forero** [comment]
aunque para ver las lectures pide password...
